# Generated by Django 4.2.7 on 2025-07-22 10:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('other', 'Other')], default='other', max_length=50)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('extracted_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['vendor'], name='processor_r_vendor_a38731_idx'), models.Index(fields=['date'], name='processor_r_date_ba3137_idx'), models.Index(fields=['amount'], name='processor_r_amount_b9d2a8_idx'), models.Index(fields=['category'], name='processor_r_categor_4e5e3c_idx'), models.Index(fields=['created_at'], name='processor_r_created_2d2ad4_idx')],
            },
        ),
    ]
